var width = 8;
var height = 9;
var area = width * height;
console.log('Area:', area);
console.log('Area is:', typeof area);
var bill = 3;
var payment = 5;
var change = payment - bill;
console.log('Your change is:', change);
console.log('Change is:', typeof change);
var quizzes = 80;
var midterm = 90;
var final = 74;
var grade = (quizzes + midterm + final) / 3;
console.log('Your grade is:', grade);
console.log('grade is:', typeof grade);
var firstName = 'Jonathan ';
var lastName = 'Byun';
var fullName = firstName + lastName;
console.log('Fullname:', fullName);
console.log('fullName is a:', typeof fullName);
var pH = 8;
var isAcidic = pH < 7;
console.log('pH less than 7 is:', isAcidic);
console.log('isAcidic is a:', typeof isAcidic);
var headCount = 300;
var isSparta = headCount > 300;
console.log('value of isSparta:', isSparta);
console.log('type of isSparta', typeof isSparta);
var motto = fullName + ' is the GOAT';
console.log('The motto is:', motto);
console.log('motto is a:', typeof motto);
