console.log('hello, world');
var h1 = document.querySelector('h1');
console.log(h1);
console.dir(h1);
var idExplanation = document.querySelector('#explanation');
console.log(idExplanation);
console.dir(idExplanation);
var hint = document.querySelector('.hint');
console.log(hint);
console.dir(hint);
var p = document.querySelectorAll('p');
console.log(p);
var example = document.querySelectorAll('.example-link');
console.log(example);
