var colors = ['red', 'white', 'blue'];
console.log('Color 1', colors[0]);
console.log('Color 2', colors[1]);
console.log('Color 3', colors[2]);
console.log('America is ' + colors[0] + ', ' + colors[1] + ', and ' + colors[2] + '.');
colors[2] = 'green';
console.log('Mexico is ' + colors[0] + ', ' + colors[1] + ', and ' + colors[2] + '.');
console.log('Colors array:', colors);
var students = ['Jon', 'Matt', 'Dave', 'Ben'];
var numberofStudents = students.length;
console.log('Number of students:', numberofStudents);
var lastIndex = numberofStudents - 1;
var lastStudent = students[lastIndex];
console.log('Last Student:', lastStudent);
console.log('students array:', students);
